### ISSUE TITLE
Bug with special session name

### ISSUE THREAD

**Issue by quentinduche** [Inria-Empenn/shanoir_downloader#29]
In the VHD cohort I have sessions (wrongly) named `HUMAINS^VHD-COHORT` but still I have to download them.

This ends up with the following error
```bash
Proxy configuration file not found. Proxy will be ignored.
get keycloak token... Traceback (most recent call last):
  File "/home/qduche/Projects/VHD/download_cohort/./vhd_dl_datasets.py", line 166, in <module>
    main()
  File "/home/qduche/Projects/VHD/download_cohort/./vhd_dl_datasets.py", line 163, in main
    s2b.download()
  File "/home/qduche/Dev/shanoir_downloader/shanoir2bids.py", line 707, in download
    self.download_subject(subject_to_search=subject_to_search)
  File "/home/qduche/Dev/shanoir_downloader/shanoir2bids.py", line 566, in download_subject
    response = shanoir_downloader.solr_search(config, args)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/qduche/Dev/shanoir_downloader/shanoir_downloader.py", line 432, in solr_search
    response = rest_post(config, url, params=params, data=json.dumps(data))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/qduche/Dev/shanoir_downloader/shanoir_downloader.py", line 276, in rest_post
    return rest_request(config, 'post', url, params=params, files=files, stream=stream, json=json, data=data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/qduche/Dev/shanoir_downloader/shanoir_downloader.py", line 259, in rest_request
    response.raise_for_status()
  File "/home/qduche/Projects/VHD/env/lib/python3.12/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 422 Client Error:  for url: https://shanoir-ofsep.irisa.fr/shanoir-ng/datasets/solr?page=0&size=200&sort=id%2CASC
```
It's ok when I change the session name `HUMAINS^VHD-COHORT` to `HUMAINS*` but still I'd like to maintain the real session name somewhere in a local file so that I do not have to tweak the Solr search.

Any idea if a special character makes the request fail ?

**Comment by alexpron** [comment]
Hello @quentinduche , I guess the solr request need to properly escape special characters as mentionned here:
+https://solr.apache.org/guide/6_6/the-standard-query-parser.html
![image](https://github.com/user-attachments/assets/faff97c4-fc58-4468-8c12-baf1b44d1a1b)

**Comment by alexpron** [comment]
I have looked a bit in the code of shanoir2bids.py and especially https://github.com/Inria-Empenn/shanoir_downloader/blob/f05750deabae8198e46cd4b28354b47ae4f591a7/shanoir2bids.py#L526 
to Empenn/shanoir_downloader/blob/f05750deabae8198e46cd4b28354b47ae4f591a7/shanoir2bids.py#L572
and indeed special character do not seems to be handled properly. 
I will create a fix for that

**Comment by alexpron** [comment]
In the PR, all special characters of the input fields (e.g. datasetName, studyName) are escaped except the * (used by some users). This solution is a compromise as it can prevent the user for using full solr search syntax but in pratice no user as done it further than * as far as I know.
I close the issue
